name: Release
on:
  push:
    branches:
      - master
jobs:
  release:
    name: Release
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: master
      - name: Create new branch from master
        uses: peterjgrainger/action-create-branch@v2.0.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          branch: 'release' 
      - name: Checkout to release branch
        uses: actions/checkout@v2
        with:
          ref: release
      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 12
      - name: Run semantic release
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN }}
        run: |
          git push origin release
          git checkout release
          npx semantic-release
      - name: Create Pull Request
        id: cpr
        uses: peter-evans/create-pull-request@v3
        with:
          token: ${{ secrets.TOKEN}}
          branch: release
          delete-branch: true
          title: 'Automated release'
          labels: release
          base: master
          reviewers: |
           ManarArabi
