name: Release
on:
  push:
    branches:
      - master
jobs:
  Release:
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout master
        uses: actions/checkout@v2
        with:
          ref: master
      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 12
      - name: install dependencies
        run: |
          npm i
      - name: run semantic release
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN }}
        run: |
          git checkout master
          git checkout -b release
          git push origin release
          git status
          npx semantic-release --branches=release
  Create-PR:
    runs-on: ubuntu-18.04
    needs: Release
    steps:
      - name: Checkout release
        uses: actions/checkout@v2
        with:
          ref: release
      - name: Create PR
        id: cpr
        uses: peter-evans/create-pull-request@v3
        with:
          token: ${{ secrets.TOKEN }}
          branch: release
          delete-branch: true
          title: 'Automated release'
          labels: release
          base: master
          reviewers: |
           ManarArabi
